name: Release

on:
  push:
    tags:
      - "v*"

env:
  DEBIAN_PACKAGE_PATH: tera-cli_linux_amd64.deb

jobs:
  linux:
    env:
      TARGET_DIR: target/release

    runs-on: ubuntu-latest
    steps:
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions/checkout@v4
      - name: Install cargo deb
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb

      - name: Build debian package
        shell: bash
        run: |
          cargo deb -p teracli -o "$DEBIAN_PACKAGE_PATH"

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ${{ env.DEBIAN_PACKAGE_PATH }}

  create_draft:
    needs: ["linux"]
    name: Create Draft
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.create-release.outputs.html_url }}
      asset_upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Release Version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4

      # TODO: here we could fetch the artifacts and reuse our freshest build.
      - name: Install tera v0.1.0
        run: |
          URL=https://github.com/chevdor/tera-cli/releases/download/v0.1.0-ae9bc49c/tera-cli_linux_amd64.deb
          wget $URL
          sudo dpkg -i tera-cli_linux_amd64.deb
          tera --version

      - name: Generate changelog
        id: change_log
        # for the first command to work, we need to checkout with fetch-depth: 0
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 ${{ env.RELEASE_VERSION }}^ )
          JSON=$(git log $LAST_TAG..HEAD \
            --pretty=format:'{ "commit": "%H", "short_sha": "%h", "author": "%an", "date": "%ad", "message": "%s"},' \
            $@ | \
            perl -pe 'BEGIN{print "{ \"since\": \"'${LAST_TAG}'\",  \"commits\": ["}; END{print "]}"}' | \
            perl -pe 's/},]/}]/')
          echo $JSON | tera --template templates/changelog.md --stdin > changelog.md

      - name: Render release notes
        run: |
          export X86_64_GNU_TGZ_URL="https://github.com/chevdor/tera-cli/releases/download/${{ env.RELEASE_VERSION }}/tera-cli-x86_64-unknown-linux-gnu.tar.gz"
          export X86_64_MUSL_TGZ_URL="https://github.com/chevdor/tera-cli/releases/download/${{ env.RELEASE_VERSION }}/tera-cli-x86_64-unknown-linux-musl.tar.gz"
          export AARCH64_GNU_TGZ_URL="https://github.com/chevdor/tera-cli/releases/download/${{ env.RELEASE_VERSION }}/tera-cli-aarch64-unknown-linux-gnu.tar.gz"
          export AARCH64_MUSL_TGZ_URL="https://github.com/chevdor/tera-cli/releases/download/${{ env.RELEASE_VERSION }}/tera-cli-aarch64-unknown-linux-musl.tar.gz"
          export DEBIAN_URL="https://github.com/chevdor/tera-cli/releases/download/${{ env.RELEASE_VERSION }}/tera-cli_linux_amd64.deb"
          export MACOS_TGZ_URL="https://github.com/chevdor/tera-cli/releases/download/${{ env.RELEASE_VERSION }}/tera-macos-${{ env.RELEASE_VERSION }}.tar.gz"
          export WINDOWS_ZIP_URL="https://github.com/chevdor/tera-cli/releases/download/${{ env.RELEASE_VERSION }}/tera-cli-aarch64-unknown-linux-musl.tar.gz"

          export CHANGELOG=$(cat changelog.md)
          tera --env --env-only --template templates/release.md > RELEASE_NOTES.md

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Tera ${{ env.RELEASE_VERSION }} (${{ env.SHORT_SHA }})
          body_path: ./RELEASE_NOTES.md
          draft: true

  publish-debian-package:
    runs-on: ubuntu-latest
    needs: ["create_draft"]
    steps:
      - uses: actions/download-artifact@v4

      - name: Upload Debian package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.asset_upload_url }}
          asset_path: "linux/tera-cli_linux_amd64.deb"
          asset_name: "tera-cli_linux_amd64.deb"
          asset_content_type: application/vnd.debian.binary-package

  publish-binaries:
    needs: ["create_draft"]
    outputs:
      sha256_macos_x86_64: ${{ steps.output-sha256.outputs.sha256_x86_64-apple-darwin }}
      sha256_macos_aarch64: ${{ steps.output-sha256.outputs.aarch64-apple-darwin }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Publish Binaries
        uses: taiki-e/upload-rust-binary-action@v1
        id: upload-binary
        with:
          bin: tera
          target: ${{ matrix.target }}
          archive: tera-cli-$target
          # SHA256 is used for Homebrew Formula
          # https://docs.brew.sh/Cask-Cookbook#stanza-sha256
          checksum: sha256,sha512
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Output SHA256
        id: output-sha256
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          sha256="$(cut -d' ' -f1 ${{ steps.upload-binary.outputs.sha256 }})"
          echo "sha256_${{ matrix.target }}=$sha256" >> $GITHUB_OUTPUT

  update-homebrew:
    needs: ["publish-binaries"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download debian package
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: ${{ env.DEBIAN_PACKAGE_PATH }}

      - name: ls
        run: ls -l
      - name: Install tera-cli
        run: |
          sudo dpkg -i "$DEBIAN_PACKAGE_PATH"

      - name: Output Release Version for Formula templates
        id: output-release-version
        run: |
          echo GITHUB_REF=$GITHUB_REF
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          RAW_VERSION=${RELEASE_VERSION:1}
          echo "RAW_VERSION=$RAW_VERSION" >> $GITHUB_OUTPUT

      # We do that before hecking out master (in case we were not in master already)
      - name: Prepare new Formula
        env:
          NAME: Tera
          DESCRIPTION: "A command line utility written in Rust to render templates using the tera templating engine"
          SITE: https://github.com
          REPO: chevdor/tera-cli
          X86_64_SHA256: ${{ needs.publish-binaries.outputs.sha256_macos_x86_64 }}
          AARCH64_SHA256: ${{ needs.publish-binaries.outputs.sha256_macos_aarch64 }}
          VERSION: ${{ steps.output-release-version.outputs.RAW_VERSION }}
        run: |
          tera --version
          tera --template templates/formula.rb --env-only > $HOME/tera.rb
          cat $HOME/tera.rb

      - name: Update Homebrew Formula
        run: |
          cp -f $HOME/tera.rb Formula/tera.rb
          git config --global user.name 'TeraBot'
          git config --global user.email 'chevdor@users.noreply.github.com'
          git commit Formula/tera.rb -m "build: new homebrew formula for ${{ env.RELEASE_VERSION }}"
